apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: cedadev/${{ values.slug }}
spec:
  type: library
  owner: user:${{ values.author.metadata.namespace }}/${{ values.author.metadata.name }}
  lifecycle: experimental
